name: alpha CI

on:
  push:
    branches: [ alpha ]
  workflow_dispatch: # manual run

jobs:
  build-and-alpha-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install ninja
        run: sudo apt-get install ninja-build

      - name: Install emsdk
        uses: mymindstorm/setup-emsdk@v10
        with:
          version: 'latest'

      - name: Echo versions
        run: |
          emcc -v
          ninja --version
          cmake --version
          node --version
          npm --version

      - name: Install and Build
        shell: bash
        run: |
          npm ci
          npm run build:ci

      - name: Publish to the npm registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}