name: alpha CI

on:
  push:
    branches: [ alpha ]
  workflow_dispatch: # manual run

jobs:
  build-and-alpha-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install ninja
        run: sudo apt-get install ninja-build

      - name: Install emsdk
        uses: mymindstorm/setup-emsdk@v10
        with:
          version: 'latest'

      - name: Echo versions
        run: |
          emcc -v
          ninja --version
          cmake --version
          node --version
          npm --version

      - name: Install and Build
        run: |
          npm ci
          npm run ci-build

      - name: Publish to the npm registry
        uses: "primer/publish@3.0.0"
        with:
          release_tag: "alpha"
          default_branch: "alpha"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}