name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch: # manual run

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          npm ci
          npm run prepare
          npm run generate-docs

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: documentation
          folder: docs

      - name: Publish to the npm registry
        uses: "primer/publish@3.0.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}